title: Ohm.codes

author: Mads Ohm Larsen

description: |-
  A blog about programming, technology and other things.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohm.codes" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-postcss-v2
  - jekyll-inline-svg
  - jekyll-redirect-from

feed:
  path: posts.atom

postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js
  cache: false
