title: Ohm.codes

author: Mads Ohm Larsen

description: >
  A blog about programming, technology and other things.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohm.codes" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-inline-svg
  - jekyll-redirect-from

feed:
  path: blog.atom

postcss:
  cache: false
